atom-editor: version bump v1.11.2
sjug/atom-editor pull request #14
Opened 2016-10-19 20:31 UTC by t-richards

2016-10-19 22:07 UTC, sjug commented
Thanks for the PR @t-richards, is there a new build strategy for atom?

2016-10-19 22:13 UTC, samueloph commented
@sjug Yes there is, that's why i didn't updated yet.

I'm gonna check @t-richards PR right now.

2016-10-19 22:54 UTC, t-richards commented
@sjug The build strategy is largely the same, but it looks like the install script only allows installation to a hardcoded path of `/usr/local`. This is why I changed the `package()` function so significantly.

2016-10-19 23:09 UTC, samueloph commented on PKGBUILD
> +  script/build --compress-artifacts
What's the motivation behind this? At first glance i see no reason to compress the binary, as we are not using the generated tarball.

2016-10-19 23:11 UTC, samueloph requested changes
Is --compress-artifacts really needed /or useful ?

2016-10-19 23:18 UTC, t-richards commented on PKGBUILD
> +  script/build --compress-artifacts
You're correct; I was thinking this flag might have some impact on the compiled `atom` binary size (it does not, in fact, have any such effect).

2016-10-19 23:20 UTC, samueloph approved these changes

2016-10-19 23:23 UTC, samueloph commented
Ok, everything's looking good now. I will wait a few hours to see if @sjug has something to say, if not, i will merge and upload it to AUR.

2016-10-20 00:07 UTC, merged

2016-10-20 00:07 UTC, sjug commented
I trust you @samueloph thanks guys for putting this together, lets push it up to the AUR.